[Etrue]
NetworkId = 2812913
SyncMode = "full"
MinervaMode = 0
LightServ = 1
LightPeers = 0
CommitteeKey = "0x6acb5ea86c6f34307b9136009d476d4a08415882897b9b94e0354eb6347441fb"
NodeCert = "0x6acb5ea86c6f34307b9136009d476d4a08415882897b9b94e0354eb6347441fb"
Host = "localhost"
Port = 8797
StandbyPort = 30311
CommitteeBase = "0x21C16f03bbF085D6908569d159Ad40BcafdB80C5"
GasPrice = 10000
EnablePreimageRecording = false
NodeType = true
EnableElection = true

[Etrue.TxPool]
NoGasUsage = true
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000
PriceBump = 10
AccountSlots = 80
GlobalSlots = 100
AccountQueue = 100
GlobalQueue = 100
Lifetime = 10800000000000

[Etrue.GPO]
Blocks = 20
Percentile = 60

[Node]
DataDir = "C:\\Users\\TM\\AppData\\Roaming\\Ethereum"
IPCPath = "geth.ipc"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth", "shh"]
WSPort = 8546
WSModules = ["net", "web3", "eth", "shh"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false
P2PNodeCert = "0x6acb5ea86c6f34307b9136009d476d4a08415882897b9b94e0354eb6347441fb"
P2PKey = "0x6acb5ea86c6f34307b9136009d476d4a08415882897b9b94e0354eb6347441fb"






