[Taiyue]
NetworkId = 2812913
SyncMode = "full"
MinervaMode = 0
CryptoType  = 2
CommitteeKey = "0x7631a11e9d28563cdbcf96d581e4b9a19e53ad433a53c25a9f18c74ddf492f75"
Host = "39.99.195.63"
Port = 30314
StandbyPort = 30312
CommitteeBase = "0x21C16f03bbF085D6908569d159Ad40BcafdB80C5"
GasPrice = 10000
EnablePreimageRecording = false
NodeType = false

[Taiyue.TxPool]
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000
PriceBump = 10
AccountSlots = 80
GlobalSlots = 100
AccountQueue = 100
GlobalQueue = 100
Lifetime = 10800000000000

[Taiyue.GPO]
Blocks = 20
Percentile = 60

[Node]
DataDir = "data"
IPCPath = "taiyue.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "yue", "shh", "personal","cpm"]
WSPort = 8546
WSModules = ["net", "web3", "yue", "shh","cpm"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30313"
EnableMsgEvents = false
P2PNodeCertFile = "./cert/p2pnodecert.pem"
P2PKey = "0xd5939c73167cd3a815530fd8b4b13f1f5492c1c75e4eafb5c07e8fb7f4b09c7c"
P2PPrivateKeyFile = "./cert/CA.key"
BootstrapNodesStr = ["enode://08b7ea4f68a685b508b1140d5745b7d43056ba4c2560106ad7cde1127e41e26abf6394651c728e3a0a70a97c571ec280678f9fefb7ad9473e595073720f3c903@39.100.84.72:30313"]